### ISSUE TITLE
README and LICENSE/COPYING file

### ISSUE THREAD

**Issue by willkg** [hylang/hygdrop#1]
This project could use a README and a LICENSE/COPYING file specifying the license this code is distributed under.

**Comment by willkg** [comment]
If someone tells me what license this should be distributed under, I'm game for doing the work and doing a pr.

**Comment by jd** [comment]
On Sun, Apr 21 2013, Will Kahn-Greene wrote:

> If someone tells me what license this should be distributed under, I'm game
> for doing the work and doing a pr.

Let's use the same as Hy.

## 

Julien Danjou
/\* Free Software hacker \* freelance consultant
   http://julien.danjou.info */
