### ISSUE TITLE
Please make hygdrop respond to private messages too

### ISSUE THREAD

**Issue by algernon** [hylang/hygdrop#6]
Sometimes one just wants to do a quick check, without spamming the channel the bot is on, so if it could respond to private queries too (by replying in a similar way), that would be very nice.

I'm willing to provide a patch in the next day or two, unless someone beats me to it.

**Comment by copyninja** [comment]
Yes indeed this is easy one just make pubmsg-handler function as handler for privmsg. I need some time to implement unless @algernon beats me ;-)

**Comment by algernon** [comment]
Oh my, I completely forgot about this one. Go ahead @copyninja, I'm not going to beat you to it anytime soon.

**Comment by copyninja** [comment]
Well its not as straight forward as I thought but I will try to fix this might take some time.
